=== cgdewar/softlogger/softlogger.dtd
<!ELEMENT softlogger (name,defaultScanRate,server,outputModule*,channel*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT defaultScanRate (#PCDATA)>

<!ELEMENT server (user,host,port?,(password|keyfile),configPoll,homeFolder)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT keyfile (#PCDATA)>
<!ELEMENT configPoll (#PCDATA)>
<!ELEMENT homeFolder (#PCDATA)>

<!ELEMENT outputModule (configValue|configElement)*>
<!ATTLIST outputModule class CDATA #REQUIRED>
<!ELEMENT configValue (#PCDATA)>
<!ATTLIST configValue name CDATA #REQUIRED>
<!ELEMENT configElement (configValue|configElement)*>

<!ELEMENT channel (defaultScanRate?,(tcp|serial),device*)>
<!ELEMENT tcp (host,port?)>

<!ELEMENT serial (comport,baud)>
<!ELEMENT comport (#PCDATA)>
<!ELEMENT baud (#PCDATA)>

<!ELEMENT device (unitId,description?,defaultScanRate?,(configRegister|dataRegister)*)>
<!ELEMENT unitId (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT configRegister (fieldName,scanRate?,registerAddress,size?,value)>
<!ELEMENT fieldName (#PCDATA)>
<!ELEMENT scanRate (#PCDATA)>
<!ATTLIST scanRate sampling (latchon|latchoff|latest|accumulate|sum|average|mean) "average">
<!ELEMENT registerAddress (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ATTLIST size type (s|u|f|int|uint|float|signed|unsigned) "unsigned">
<!ELEMENT value (#PCDATA)>

<!ELEMENT dataRegister (fieldName,scanRate?,registerAddress,size?,dataFunction?,guid)>
<!ELEMENT dataFunction (#PCDATA)>
<!ATTLIST dataFunction type (expression|lookupTable|customClass) #REQUIRED>
<!ELEMENT guid (#PCDATA)>

=== cgdewar/softlogger/softlogger.xml
<!--
  Copyright (c) 2013 Charles Hache. All rights reserved. 
  
  This file is part of the softlogger project.
  softlogger is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  softlogger is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with softlogger.  If not, see <http://www.gnu.org/licenses/>.
  
  Contributors:
      Charles Hache - initial API and implementation
-->
<!DOCTYPE softlogger SYSTEM "softlogger.dtd">
<softlogger>
	<name>Test Logger</name>
	<defaultScanRate>500</defaultScanRate> <!-- default scan rate in milliseconds -->
	<channel>
		<defaultScanRate>333</defaultScanRate> <!-- default scan rate for this channel, overrides Softlogger scan rate -->
		<tcp>
			<host>127.0.0.1</host>
			<port>5020</port>
		</tcp>
		<!--
		<serial>
			<comport>/dev/ttyUSB0</comport>
			<baud>9600</baud>
		</serial>
		-->
		<device>
			<!-- devices can each have a scan rate as well, which overrides their channel
			and softlogger default scan rates. -->
			<unitId>15</unitId>
			<description>WattsOn</description>
			<defaultScanRate>800</defaultScanRate>
			<retryInterval>5000</retryInterval>
			<maxRetryInterval>30000</maxRetryInterval>
			<outputModule class="ca.brood.softlogger.dataoutput.DebugOutputModule">
				<configValue name="logIntervalSeconds">5</configValue>
			</outputModule>
			<outputModule class="ca.brood.softlogger.dataoutput.CSVOutputModule">
				<configValue name="logIntervalSeconds">5</configValue>
				<configValue name="newFilePeriodMinutes">1</configValue>
				<configValue name="csvSubdirectory">csv</configValue>
				<configValue name="completedFileDirectory">csv/completed</configValue>
			</outputModule>
			<outputModule class="ca.brood.softlogger.dataoutput.DBOutputModule">
				<configValue name="logIntervalSeconds">1</configValue>
				<configValue name="dbUser">softie</configValue>
				<configValue name="dbPassword">password</configValue>
				<configValue name="dbSchema">softlogger</configValue>
				<configValue name="dbHost">127.0.0.1</configValue>
				<!-- <configValue name="dbPort">2222</configValue> -->
			</outputModule>
			<configRegister>
				<fieldName>Config coil 1 true</fieldName>
				<registerAddress>000001</registerAddress>
				<value>true</value>
			</configRegister>
			<configRegister>
				<fieldName>Config value 1</fieldName>
				<registerAddress>400003</registerAddress>
				<size type="signed">2</size> 
				<value>-5</value>
			</configRegister>
			<dataRegister>
				<fieldName>Measurement 3-1</fieldName>
				<registerAddress>300001</registerAddress>
				<guid>D3M01</guid>
			</dataRegister>
			<dataRegister>
				<fieldName>Measurement 3-2</fieldName>
				<registerAddress>300002</registerAddress>
				<size>2</size>
				<guid>D3M02</guid>
			</dataRegister>
			<dataRegister>
				<fieldName>Measurement 3-3</fieldName>
				<registerAddress>300003</registerAddress>
				<guid>D3M03</guid>
			</dataRegister>
			<dataRegister>
				<fieldName>Measurement 4-6</fieldName>
				<registerAddress>400006</registerAddress>
				<size type="float">2</size>
				<dataFunction class="ca.brood.softlogger.datafunction.ExpressionParserDataFunction">pi*$*1000/sqrt(e)</dataFunction>
				<guid>D3M04</guid>
			</dataRegister>
			<dataRegister>
				<fieldName>Measurement 4-8</fieldName>
				<registerAddress>400008</registerAddress>
				<size type="float">2</size>
				<guid>D3M5</guid>
			</dataRegister>
			<dataRegister>
				<fieldName>Measurement 0-1</fieldName>
				<registerAddress>000001</registerAddress>
				<guid>D3M6</guid>
			</dataRegister>
			<dataRegister>
				<fieldName>Measurement 1-1</fieldName>
				<registerAddress>100001</registerAddress>
				<guid>D3M7</guid>
			</dataRegister>
			<dataRegister>
				<fieldName>Measurement 4-3</fieldName>
				<registerAddress>400003</registerAddress>
				<size type="signed">2</size>
				<guid>D3M8</guid>
			</dataRegister>
		</device>
	</channel>
<!--	
	<virtualRegister guid="D4M04">
		<fieldName>Power</fieldName>
		<function>measurement(D4M02)*measurement(D4M03)</function>
	</virtualRegister>
-->
</softlogger>
